/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bisnode.opa.spring.security;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
